image: python:3

before_script:
 - pip install flake8
 - pip install pytest
 - pip install pytest-cov

test:
  script:
    - python3 -m flake8 algo/
    - python3 -m pytest --cov algo algo/test_lr.py 
  tags:
    - common
